# Generated by Django 3.0.6 on 2020-07-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
