# Generated by Django 3.0.6 on 2020-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200715_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
