# Generated by Django 3.0.6 on 2020-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200719_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='para',
            field=models.TextField(default='para'),
        ),
    ]
