# Generated by Django 3.0.6 on 2020-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_article_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
