# Generated by Django 3.0.6 on 2020-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_article_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about1', models.TextField()),
                ('about2', models.TextField()),
            ],
        ),
    ]
